sudo: required
services:
  - docker

before_install:
  - docker build -t scubadude/docker-react -f Dockerfile.dev .

script:
  - docker run scubadude/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-974826260669"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_ke:
    secure: "$AWS_SECRET_KEY " 